### ISSUE TITLE
about MAX depth

### ISSUE THREAD

**Issue by wangjiyuan9** [fengziyue/DynamicDepth#12]
Hello！Dear Author ,thank you for your contribution!
In the code, I found that you set MAX depth as 80 in both Kitti and Cityscape. Actually, I wonder:
1.The unit of the num in the ".npy" file. Are they in meter?
2. Why always use 80 as the MAX depth? I checked the MAX value of manydepth cityscape gt_depth is 473.5748014025198
And the MAX value of Kitti dataset gt_depth is about 82. So I think the "80" is ok for Kitti but not adapted to Cityscape?

**Comment by fengziyue** [comment]
Hi, thank you so much for your interest!
1, Yes, the unit is meters.
2, Most of the existing works only evaluate the depths within 80 meters, we follow the convention for a fair comparison. There are also some long-range-focused methods that estimate up to 200 meters in the Waymo dataset.

**Comment by wangjiyuan9** [comment]
Thanks!
