### ISSUE TITLE
The issue of dynamic regional indicators

### ISSUE THREAD

**Issue by WangXuCh** [fengziyue/DynamicDepth#16]
May I ask how you calculate the indicators of dynamic regions? Can you provide some source code? Because the metrics generated by my code look incorrect. Thank you!

**Comment by fengziyue** [comment]
Hi:

Thank you so much for your interest in our work and sorry for the late reply!

I use an off-the-shelf semantic segmentation model to generate the masks and mark `vehicles` `pedestrians` and `cyclists` as dynamic object.

**Comment by WangXuCh** [comment]
> Hi:
> 
> Thank you so much for your interest in our work and sorry for the late reply!
> 
> I use an off-the-shelf semantic segmentation model to generate the masks and mark `vehicles` `pedestrians` and `cyclists` as dynamic object.

May I ask which segmentation model you are using?

**Comment by fengziyue** [comment]
I was using EffcientPS as stated in the paper
