### ISSUE TITLE
About  Prediction Visualization

### ISSUE THREAD

**Issue by WangXuCh** [fengziyue/DynamicDepth#19]
<img width="292" alt="d58caf25b4ec4cbd9ce78a7a822315e" src="https://github.com/AutoAILab/DynamicDepth/assets/105144155/f2c7d1ad-293a-494d-b497-46c0103b0270">
May I ask, which library was used to implement this visualization method? Do you have the corresponding code?

**Comment by fengziyue** [comment]
Hi:

Thank you for your interest, I was using open3d with rendering points as spheres. I don't have access to this code at the moment.

**Comment by WangXuCh** [comment]
> Thank you for your interest, I was using open3d with rendering points as spheres. I don't have access to this code at the moment.

Thank you!
